version: "3.3"
services:

  redis: 
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      main:
        aliases:
          - redis

  php:
    build: ./php-fpm
    container_name: php
    depends_on:
      - redis
    volumes:
      - ./app:/usr/local/apache2/htdocs/app
    networks:
      main:
        aliases:
          - php
networks:
  main:

   
      
