version: "3.3"
services:

  redis: 
    image: redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  mysql: 
    # Build
    build: ./mariadb/docker/10.4
    container_name: mysql
    command: mysqld --sql_mode=""
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/:/var/mariadb
  php:
    build: ./php-fpm
    container_name: php
    volumes:
      - ./app:/var/www/app
      - ./app/opcache:/var/www/app/opcache

  php56:
    build: ./php56-fpm
    container_name: php56
    volumes:
      - ./app:/var/www/app
      - ./app/opcache:/var/www/app/opcache

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
      - php56
      - mysql
      - redis
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./app:/var/www/app
      - ./app/opcache:/var/www/app/opcache
      
