version: "3.3"
services:

  redis: 
    image: redis
    # build: ./redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  php:
    build: ./php-fpm
    container_name: php
    depends_on:
      - redis
    volumes:
      - ./app:/usr/local/apache2/htdocs/app

  httpd:
    build: ./httpd/2.4/alpine
    container_name: httpd
    ports:
      - "80:80"
    depends_on:
      - php
      - redis
    volumes:
      - ./logs/httpd:/etc/httpd/logs
      - ./app:/usr/local/apache2/htdocs/app

   
      
